export const database = [
    { term: "MACHINE LEARNING", clue: "What do you call a bunch of 'IF' statements wearing a trench coat?!" },
    { term: "P-HACKING", clue: "What is the scientific term for torturing the data until it finally confesses?!" },
    { term: "CORRELATION", clue: "Identify Causation's less committed, highly toxic cousin!" },
    { term: "OUTLIER", clue: "What is the name of the single data point that ruined your entire weekend plans?!" },
    { term: "P = 0.049", clue: "Publish it. Become a professor. Ignore the guilt. What is this magic number?!" },
    { term: "BIG DATA", clue: "What is the corporate buzzword for 'It just doesn't fit in Excel anymore'?!" },
    { term: "NULL HYPOTHESIS", clue: "Identify the ultimate mathematical buzzkill for your beautifully crafted research paper!" },
    { term: "BAYESIAN", clue: "What do we call the act of changing your mind as you go and disguising it as advanced math?!" },
    { term: "A/B TESTING", clue: "What is the process of arguing over button colors, but using mathematics to justify it?!" },
    { term: "OVERFITTING", clue: "What happens when your model predicts the past perfectly but fails spectacularly in real life?!" },
    { term: "DATA SCIENTIST", clue: "Who is the highly paid corporate psychic that uses Python instead of tarot cards?!" },
    { term: "PIE CHART", clue: "Name the visual atrocity that is completely useless and makes statisticians cry!" },
    { term: "NORMAL DISTRIBUTION", clue: "What is the shape of the lie we tell ourselves about how the real world works?!" },
    { term: "SPURIOUS CORRELATION", clue: "Ice cream sales cause shark attacks! What is this statistical phenomenon called?!" },
    { term: "RANDOM SEED", clue: "What is the magic number you set to 42 so your code works exactly the same way every time?!" },
    { term: "ARTIFICIAL INTELLIGENCE", clue: "What do you call a PowerPoint presentation about Machine Learning?!" },
    { term: "CHATGPT", clue: "Who is the digital intern that confidently lies to you but sounds really smart?!" },
    { term: "REGRESSION", clue: "What is the act of drawing a straight line through a cloud of sadness?!" },
    { term: "EXCEL", clue: "Name the world's most popular database, much to every developer's absolute dismay!" },
    { term: "SQL", clue: "SELECT * FROM my_problems WHERE solution IS NULL! What language is this?!" },
    { term: "PYTHON", clue: "Whitespace matters! What is the name of this highly sensitive programming language?!" },
    { term: "R", clue: "What is the language that makes statisticians feel like real programmers?!" },
    { term: "JUPYTER NOTEBOOK", clue: "Identify the chaotic graveyard of unnamed variables and out-of-order execution cells!" },
    { term: "CSV", clue: "What is the cockroach of data formats that will easily survive a nuclear apocalypse?!" },
    { term: "JSON", clue: "What format consists entirely of curly braces containing your impending migraine?!" },
    { term: "PANDAS", clue: "It's not a cute bear, it's 50 different ways to merge a dataframe and fail! What is it?!" },
    { term: "GITHUB", clue: "Where exactly does your terrible code go to be judged by strangers?!" },
    { term: "DASHBOARD", clue: "What is the colorful screen that executives look at exactly once and never again?!" },
    { term: "KPI", clue: "Name the highly manipulated metric that determines your year-end bonus!" },
    { term: "DATA LAKE", clue: "What do we call a massive digital swamp where structured data goes to drown?!" },
    { term: "CLOUD COMPUTING", clue: "What is the fancy term for 'someone else's computer that you pay hourly for'?!" },
    { term: "HADOOP", clue: "What was that yellow elephant everyone talked about in 2014 and then quietly abandoned?!" },
    { term: "BLOCKCHAIN", clue: "Identify the hyper-expensive cryptographic solution desperately looking for a problem!" },
    { term: "DATA ENGINEERING", clue: "What is the digital plumbing work nobody respects until the toilet overflows?!" },
    { term: "ETL", clue: "Extract, Torture, Load! What is this abbreviation?!" },
    { term: "WEBSCRAPING", clue: "What is the technical term for legally ambiguous copy-pasting at an industrial scale?!" },
    { term: "API", clue: "What is a polite way for two computers to absolutely scream at each other?!" },
    { term: "REGEX", clue: "You had a problem. You used this. Now you have two problems! What is it?!" },
    { term: "K-MEANS", clue: "What algorithm groups people who are equally confused into distinct clusters?!" },
    { term: "DECISION TREE", clue: "What is basically just a flowchart that went to grad school and got an ego?!" },
    { term: "RANDOM FOREST", clue: "When one decision tree is bad, so you plant 500 bad ones! What is this called?!" },
    { term: "NEURAL NETWORK", clue: "What is just matrix multiplication dressed up in a biological Halloween costume?!" },
    { term: "GRADIENT DESCENT", clue: "What optimization method is like blindly walking down a mountain in the fog while drunk?!" },
    { term: "BACKPROPAGATION", clue: "What is the act of blaming everyone else backwards until the error is minimized?!" },
    { term: "EPOCH", clue: "Doing the exact same thing again and desperately hoping for a better result!" },
    { term: "HYPERPARAMETERS", clue: "What are the random numbers you guess until the accuracy stops being embarrassing?!" },
    { term: "CROSS VALIDATION", clue: "What is the process of lying to your model to make sure it's not lying to you?!" },
    { term: "UNDERFITTING", clue: "What do we call it when your predictive model is as clueless as your project manager?!" },
    { term: "BIAS", clue: "What is the systemic prejudice your algorithm accidentally learned from historical data?!" },
    { term: "VARIANCE", clue: "What happens when your model has an absolute freakout over a single new data point?!" },
    { term: "CONFUSION MATRIX", clue: "What table perfectly describes your state of mind during a stakeholder presentation?!" },
    { term: "ACCURACY", clue: "What metric looks fantastic until you realize 99% of your data is just zeros?!" },
    { term: "PRECISION", clue: "What is the metric for being exactly wrong, but in a very tight, consistent grouping?!" },
    { term: "RECALL", clue: "Trying to remember what your code from three months ago actually does! What is this?!" },
    { term: "F1 SCORE", clue: "What metric was invented purely because nobody could agree on Precision or Recall?!" },
    { term: "ROC CURVE", clue: "What graph is used to mathematically prove your model is slightly better than flipping a coin?!" },
    { term: "AUC", clue: "The area under the curve, and also the sound you make when the code crashes!" },
    { term: "LOGISTIC REGRESSION", clue: "Who is Linear Regression's cooler cousin who only deals in absolute categories?!" },
    { term: "TIME SERIES", clue: "What is the art of trying to predict the future using a chart that looks like an EKG?!" },
    { term: "ARIMA", clue: "What model sounds like a Japanese dessert but is actually pure mathematical pain?!" },
    { term: "STATIONARITY", clue: "What is the assumption that the world hasn't changed in twenty years just to make the math work?!" },
    { term: "AUTOCORRELATION", clue: "What is it called when yesterday's bad decisions directly cause today's bad decisions?!" },
    { term: "MARKOV CHAIN", clue: "What is a memoryless statistical process, much like a goldfish or an executive sponsor?!" },
    { term: "MONTE CARLO", clue: "What method involves rolling a million digital dice and pretending it is rigorous science?!" },
    { term: "AGILE", clue: "Moving the goalposts every two weeks and calling it a methodology!" },
    { term: "SCRUM MASTER", clue: "Who is the adult whose entire job is asking if you moved your Jira ticket?!" },
    { term: "STANDUP MEETING", clue: "What is the daily 15-minute event where people invent things they supposedly did yesterday?!" },
    { term: "MVP", clue: "What is the broken piece of absolute trash we are shipping to live users today?!" },
    { term: "TECH DEBT", clue: "What do we call the code problems left for Future You, a person you actively despise?!" },
    { term: "STACK OVERFLOW", clue: "Identify the actual brains behind every single senior developer's lucrative career!" },
    { term: "DOCKER", clue: "Well, it works on my machine... so we shipped my machine! What tool is this?!" },
    { term: "KUBERNETES", clue: "Because managing one server wasn't painful enough, let's manage fifty! What is it?!" },
    { term: "GIT BLAME", clue: "What command do you run right before realizing you were the one who wrote the broken code?!" },
    { term: "MERGE CONFLICT", clue: "What happens when two developers disagree, and the computer makes it your problem?!" },
    { term: "PRODUCTION", clue: "Name the terrifying place where your code goes to break in front of real users!" },
    { term: "STAGING", clue: "What is the fake environment that accurately mimics absolutely nothing?!" },
    { term: "LOCALHOST", clue: "Name the magical fantasy land where all code works perfectly on the first try!" },
    { term: "CACHE", clue: "What is the reason your website update isn't showing up, 99% of the time?!" },
    { term: "HEISENBUG", clue: "What is a software bug that completely disappears the exact moment you try to look at it?!" },
    { term: "SPAGHETTI CODE", clue: "What do you call programming logic so tangled it belongs in an Italian restaurant?!" },
    { term: "REFACTORING", clue: "What is the process of breaking code that currently works just to make it look prettier?!" },
    { term: "REGRESSION TESTING", clue: "What is making sure the shiny new feature didn't completely destroy the old features?!" },
    { term: "UNIT TEST", clue: "What is the code you write to prove your other code isn't as bad as you think it is?!" },
    { term: "CI/CD", clue: "What pipeline is used for automatically deploying your mistakes to production at lightning speed?!" },
    { term: "MEAN", clue: "What is the average amount of pure anger a data set causes you?!" },
    { term: "MEDIAN", clue: "What is the only central metric that doesn't get completely ruined by Elon Musk's net worth?!" },
    { term: "MODE", clue: "What is the number that shows up the most, exactly like your ex at a party?!" },
    { term: "STANDARD DEVIATION", clue: "What measures how far off the rails your project has gone from the original timeline?!" },
    { term: "Z-SCORE", clue: "What tells you mathematically exactly how weird you are compared to a normal population?!" },
    { term: "HISTOGRAM", clue: "What is just a bar chart that went on a diet and squeezed all the bars together?!" },
    { term: "SCATTER PLOT", clue: "What chart looks like someone literally sneezed dots onto your computer screen?!" },
    { term: "BOX PLOT", clue: "What is the weird chart only statisticians understand, featuring whiskers?!" },
    { term: "T-TEST", clue: "What is comparing two things to see if they are different, but with math?!" },
    { term: "ANOVA", clue: "What is basically just a T-Test that brought all its friends to the party?!" },
    { term: "CHI-SQUARE", clue: "What test do you use to see if your categorical data is completely made up?!" },
    { term: "DEGREES OF FREEDOM", clue: "What is the number of choices you have left before the math completely breaks down?!" },
    { term: "CONFIDENCE INTERVAL", clue: "What is a range of numbers covering up the fact that you have absolutely no idea?!" },
    { term: "TYPE I ERROR", clue: "The boy who cried wolf: What statistical tragedy is this?!" },
    { term: "TYPE II ERROR", clue: "Missing the wolf entirely while it brutally eats your sheep! What error is this?!" },
    { term: "HYPOTHESIS", clue: "What is the educated guess you are about to brutally and mathematically disprove?!" },
    { term: "PROBABILITY", clue: "What is Math's fancy way of saying 'It might happen, I honestly don't know'?!" },
    { term: "BAYES THEOREM", clue: "What formula is used for updating your beliefs only AFTER you've already made the mistake?!" },
    { term: "LAW OF LARGE NUMBERS", clue: "If you do it enough times, the weird stuff cancels out! What rule is this?!" },
    { term: "CENTRAL LIMIT THEOREM", clue: "Everything is a bell curve if you squint hard enough! What theorem states this?!" },
    { term: "EXTRAPOLATION", clue: "Assuming the trend will continue forever until it ruins your company! What is this called?!" },
    { term: "INTERPOLATION", clue: "Guessing the missing pieces and praying to god nobody checks your work! What is this?!" },
    { term: "MISSING DATA", clue: "What are the black holes in your spreadsheet that consume your sanity and time?!" },
    { term: "IMPUTATION", clue: "Making up fake data to fill the holes and feeling dirty about it afterwards!" },
    { term: "ONE-HOT ENCODING", clue: "What is the process of turning simple words into a massive, unreadable grid of zeros and ones?!" },
    { term: "DIMENSIONALITY REDUCTION", clue: "Squishing a 3D object into 2D purely because your laptop is crying and overheating!" },
    { term: "PCA", clue: "What technique is just rotating your data around until it looks slightly more organized?!" },
    { term: "NLP", clue: "Teaching a shiny rock how to read Shakespeare and write spam emails! What field is this?!" },
    { term: "TOKENIZATION", clue: "What is chopping sentences into pieces like a linguistic serial killer called?!" },
    { term: "WORD EMBEDDING", clue: "Turning human language into math just so a computer can deeply misunderstand it!" },
    { term: "SENTIMENT ANALYSIS", clue: "An algorithm sweating nervously trying to figure out if a tweet is sarcastic or not!" },
    { term: "CHURN RATE", clue: "What metric tracks the speed at which customers realize your product is terrible?!" },
    { term: "LIFETIME VALUE", clue: "How much money we can extract from a user before they die or delete the app! What is this?!" },
    { term: "CUSTOMER ACQ COST", clue: "How much money it costs to effectively bribe a user into downloading your app!" },
    { term: "CONVERSION RATE", clue: "What is the percentage of people who accidentally clicked the 'Buy' button?!" },
    { term: "HACKATHON", clue: "24 hours of no sleep, energy drinks, and code that will literally never be used!" }
];

